variables:
  - group: New variable group 26-May
#trigger when branch starts with feature/* and path given 
trigger:
 branches:
  include:
  - feature/*
#pull request 
pr: 
 branches:
  include:
  - uat
  

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: SFbuild
    jobs:
  - job: SF Build JOb
    template: .pipeline/build-deploy.yml
    parameters:
    - name: SF_CLIENT_ID
    - name: SF_USERNAME
    - name: SF_LOGIN_URL
    - name: SECURE_FILE_NAME
