trigger:
  - feature/*

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: build
    jobs: 
      - job: buildjob
        steps:
          - script: echo Hello, world!
            displayName: 'Run a one-line script'

          - script: |
              echo Add other tasks to build, test, and deploy your project.
              echo See https://aka.ms/yaml
            displayName: 'Run a multi-line script'

          - script: |
              npm install @salesforce/cli --global
              sf --version
            displayName: Install Salesforce CLI 

          - checkout: self
            fetchDepth: 0
            displayName: checkout to correct commit 

          # Authenticate With SF org
          - script: |
              echo $(SF_CLIENTID)
              echo $(SF_LOGINURL)
              echo $(SF_USERNAME)
            displayName: Print Variables

          - task: DownloadSecureFile@1
            name: securefile
            displayName: download certificate JWT
            inputs:
              secureFile: 'server.key'

          - script: sf org login jwt --username $(SF_USERNAME) --jwt-key-file $(securefile.sourceFilePath) --client-id $(SF_CLIENTID) --set-default --alias ci-org --instance-url $(SF_LOGINURL)
            displayName: Authenticate to Salesforce