variables:
  - group: 'New variable group 26-May'

trigger:
  branches:
    include:
      - feature/*

pr:
  branches:
    include:
      - uat

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: SFbuild
    jobs:
      - template: pipeline/build-deploy.yml
        parameters:
          SF_CLIENT_ID: $(SF_CLIENTID)
          SF_USERNAME: $(SF_USERNAME)
          SF_LOGIN_URL: $(SF_LOGINURL)
          SECURE_FILE_NAME: 'server.key'

  - stage: Test
    jobs:
      - job: SF_Test_Job
        steps:
          - script: echo "Running tests..."