parameters:
  - name: SF_CLIENT_ID
    type: string
  - name: SF_USERNAME
    type: string
  - name: SF_LOGIN_URL
    type: string
  - name: SECURE_FILE_NAME
    type: string

jobs:
  - job: buildJob
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - script: echo Reusable Job
        displayName: 'Print Status'